### ISSUE TITLE
[BUG] Exception Error: java.lang.NoClassDefFoundError: net/minecraft/class_1113

### ISSUE THREAD

**Issue by windy664** [LokeYourC3PH/Industrial-ReZolution#1]
**Description:**
I encountered an exception while using the project (or server), leading to a program crash. The detailed information of the exception is as follows:
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_1113
	at me.steven.indrev.WCustomTabPanel.add(WCustomTabPanel.java:97)
	...
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1113
	...
In the stack trace, a java.lang.NoClassDefFoundError exception occurred, indicating that the class named net.minecraft.class_1113 could not be found at runtime. The exception seems to be triggered in the me.steven.indrev.WCustomTabPanel.add method and me.steven.indrev.gui.screenhandlers.machines.RancherScreenHandler constructor.

**Steps to Reproduce:**
- Steps to reproduce this behaviour

**Technical Information:**
 - Minecraft: 1.20.1
 - Fabric API: 0.15.6
 - Industrial Revolution: 1.16.5
 - Modpack: 

**Logs:**
- Use a paste service, do not paste the logs directly here.
- https://pastebin.com/KX0pj43c

**Details:**

**Comment by LokeYourC3PH** [comment]
I have merely made the updates to the mod that were necessary in order for it to run on Fabric 15.x, and done no other changes except for also fixing the bugged name in the Creative Menu. As such, this is an issue with the base version of the mod. However, I will see what I can do, but I cannot promise that I will be able to fix it or even fix it at all since it simply isn't my responsibility considering that I am not the maintainer nor owner of this mod.

Though like I said, that being said, I will when I have ample time (and given that I have interest), try to look into it and push a new build with the fix _**IF**_ I manage to identify why this even occurs, because this does not occur for me and I can open the Rancher just fine without any crash occurring. I'd advise you to try using a lower Fabric API for testing, such as 0.15.3. If the issue keeps occurring with 0.15.3, then please let me know. If it does not, also let me know, because then it's a problem with the newer Fabric versions.

**Comment by LokeYourC3PH** [comment]
Also, except for just downgrading your Fabric API version to 0.15.3, also please let me know which other mods you're using.

**Comment by LokeYourC3PH** [comment]
@windy664 Without a reply from you with more information that I requested of you, I cannot help you and I cannot fix this bug.

The issue will henceforth be closed in 2 days if there's no reply by then.

**Comment by LokeYourC3PH** [comment]
User not responding - Issue closed
